video_data = [
    ('tLIsVCI1hLM', 'ME SENTINDO UMA PRINCESA | Disney Vlog'),
    ('0B_lNbF_x4M', 'O DIA QUE EU FUI PRA EUROPA KKKKK'),
    ('_v-2Ilz15QA', 'O DIA QUE EU FUI PRA ARGENTINA KKKKK (do nada)'),
    ('svRkheX418o', 'O DIA QUE EU FUI PRO CHILE KKKKKKKKK (do nada)'),
    ('XKYY1vR8fLo', 'UM DOIDO EM PARIS...'),
    ('31pEiIiDPDo', 'AS AVENTURAS DE UM ESQUISITO EM BARCELONA...'),
    ('VbN9DIHYioA', 'UM DOIDO NA GRÉCIA...'),
    ('K2qn3lL-Miw', 'Se eu for EXPULSO NA GRÉCIA, o vídeo acaba...'),
    ('bL73rKwCUmQ', 'UM DOIDO EM MADRID...'),
    ('4O8xJgGaPEw', '10 minutos de um POBRE na SUIÇA.'),
    ('Ff0sKF0rgc8', 'UM DOIDO na NEVE PELA PRIMEIRA VEZ KKKKKKK'),
    ('NpIScVRALCE', 'UM DOIDO EM ROMA...'),
    ('6tyG6Ifa6qo', 'Llanfairpwllgwyngyllgogerichwyrndrobullllantysiligogogoch'),
    ('dBW8DmpPU1o', 'UM DOIDO NA CROÁCIA...'),
    ('OIY_9531CDY', 'Fui pro PAÍS MAIS RICO do MUNDO (pra bisbilhotar)'),
    ('mF-kVZdKmi4', 'I went to the 250-YEAR-OLD AMUSEMENT PARK 💀 in AUSTRIA'),
    ('LF3oYcPiZ_o', 'The Adventure of 3 Countries (in the same video) 🌎'),
    ('x9MEZsleLrw', 'Fui pro PAÍS ESCONDIDO que NINGUÉM CONHECE'),
    ('BhYKIJ-Ox7o', 'ESSE PAÍS TEM os PIORES PONTOS TURÍSTICOS'),
    ('nJnfxM-5VZ4', 'My arrival in Japan lol'),
    ('IhOKoIFFyEQ', '1 HORA DE AVENTURAS EM TÓQUIO kkkkkkk'),
    ('aeqBFvo-sVE', 'Eu dormi no PIOR HOTEL DO JAPÃO (nota 1,7)'),
    ('HMqPiRRISq8', '24h PROVANDO COMIDAS DO JAPÃO (passei mal?)'),
    ('3MysOnBKWkI', 'visitei o TOBA DO JAPÃO...'),
    ('HMwDDaAws9o', 'I went to Disneyland Paris (I didn\'t know it existed).'),
    ('YkGmU4__7Yg', 'UM DOIDO NO VULCÃO DO JAPÃO (Monte Fuji)'),
    ('Y1G4InDwn_E', 'South Korea is crazy! LOL'),
    ('njob5E5H7IU', 'A madman on the Great Wall of China'),
    ('xQnpRE84aK8', 'Nobody Knows What\'s in This Video'),
]
for vid, title in video_data:
    lines = [
        '  {',
        f"    id: 'yt-{vid}',",
        f"    title: '{title.replace("'", "\\'")}',",
        f"    externalThumbnail: 'https://img.youtube.com/vi/{vid}/maxresdefault.jpg',",
        "    duration: '--:--',",
        "    ageRating: '3+',",
        "    categoryId: 'kaykeflex',",
        "    subcategoryId: 'kaykeflex-kaike-e-julia',",
        "    category: 'Kaykeflex',",
        f"    description: '{title.replace("'", "\\'")}',",
        f"    videoUrl: 'https://www.youtube.com/watch?v={vid}',",
        f"    youtubeId: '{vid}',",
        '  },',
    ]
    print('\n'.join(lines))
